name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    environment: staging
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting Today is $DAY_OF_WEEK!"
